application: hex-lang
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /docs
  static_dir: docs

- url: /.*
  static_files: index.html
  upload: index.html